### ISSUE TITLE
mutual-TLS certificate and key not set

### ISSUE THREAD

**Issue by kg0r0** [yescom/yes-nodejs-backend#1]
This demo will result in an error during client authentication because the client certificate and private key are missing.
If there is a way to generate the correct client certificate, please let me know.

<details>
  <summary> View logs</summary>

```
> oidc-backend@1.0.0 start
> node index.js

running on 3000
Error: Error: ENOENT: no such file or directory, open '/Users/kg0r0/git-workspace/yes-nodejs-backend/routes/../config/cert.pem'
    at Object.openSync (node:fs:506:3)
    at Object.readFileSync (node:fs:402:35)
    at Client.client.<computed> (/Users/kg0r0/git-workspace/yes-nodejs-backend/routes/yes.js:129:35)
    at Client.request (/Users/kg0r0/git-workspace/yes-nodejs-backend/node_modules/openid-client/lib/helpers/request.js:31:19)
    at Client.authenticatedPost (/Users/kg0r0/git-workspace/yes-nodejs-backend/node_modules/openid-client/lib/helpers/client.js:145:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.grant (/Users/kg0r0/git-workspace/yes-nodejs-backend/node_modules/openid-client/lib/client.js:1214:22)
    at async Client.callback (/Users/kg0r0/git-workspace/yes-nodejs-backend/node_modules/openid-client/lib/client.js:462:24)
/Users/kg0r0/git-workspace/yes-nodejs-backend/node_modules/openid-client/lib/helpers/request.js:37
    throw new TypeError('mutual-TLS certificate and key not set');
          ^

TypeError: mutual-TLS certificate and key not set
    at Client.request (/Users/kg0r0/git-workspace/yes-nodejs-backend/node_modules/openid-client/lib/helpers/request.js:37:11)
    at Client.authenticatedPost (/Users/kg0r0/git-workspace/yes-nodejs-backend/node_modules/openid-client/lib/helpers/client.js:145:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.grant (/Users/kg0r0/git-workspace/yes-nodejs-backend/node_modules/openid-client/lib/client.js:1214:22)
    at async Client.callback (/Users/kg0r0/git-workspace/yes-nodejs-backend/node_modules/openid-client/lib/client.js:462:24)
```
</details>

**Comment by danielfett** [comment]
Please refer to Step 1 of the README for pyyes: https://github.com/yescom/pyyes

I'll update the README in this project accordingly.

**Comment by kg0r0** [comment]
@danielfett 
Thank you for your reply.
I was able to find the Sandbox Demo Client Data from the link and solved the problem!!

However, the ``/videocall/patient`` specified by YES_NEXT_URL does not seem to exist.
I thought it might be better to specify ``/yes/session/claims``.
